host: "0.0.0.0"
port: 4222

http: "0.0.0.0:8222"

max_payload: 1MB

max_pending: 8MB

max_connections: 256

debug: false
trace: false
logtime: true

jetstream {
  store_dir: "/data"

  max_memory_store: 64MB

  max_file_store: 2GB
}

accounts {
  ARGUS: {
    jetstream: {
      max_mem: 32MB
      max_file: 1536MB

      max_streams: 24
      max_consumers: 128

      disk_max_stream_bytes: 512MB
      memory_max_stream_bytes: 32MB

      max_bytes_required: true
    }

    users: [
      { user: "argus", password: $NATS_ARGUS_PASSWORD }
      { user: "agent", password: $NATS_AGENT_PASSWORD }
    ]

  }
}

